name: CI/CD Pipeline for Airflow + DBT + Snowflake

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Also run for PRs to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use your Python version

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv airflow_venv
          source airflow_venv/bin/activate
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake apache-airflow snowflake-connector-python pandas

      - name: Configure DBT Profile
        run: |
          mkdir -p ~/.dbt
          echo "airflow_proj:
            outputs:
              dev:
                type: snowflake
                account: mn92153.ap-southeast-1
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ACCOUNTADMIN
                database: PANDAS
                warehouse: COMPUTE_WH
                schema: DEV_LAYER
                threads: 1
            target: dev" > ~/.dbt/profiles.yml

      - name: Run Data Load Script (`main.py`)
        run: |
          
          source /home/hp/airflow_venv/bin/activate && python /home/hp/airflow_venv/airflow_proj/Scripts/main.py



      - name: Run DBT Models
        run: |
          source airflow_venv/bin/activate
          cd airflow_venv/airflow_proj  # Move to DBT project directory
          dbt run --models DEV_LAYER
          dbt run --models PROD_LAYER 

      - name: Deploy Airflow DAGs
        run: |
          mkdir -p ~/airflow/dags
          cp -r airflow_dags/* ~/airflow/dags/
          airflow db upgrade
          airflow dags list

      - name: Start Airflow Services
        run: |
          source airflow_venv/bin/activate
          nohup airflow scheduler > ~/airflow/scheduler.log 2>&1 &
          nohup airflow webserver -p 8080 > ~/airflow/webserver.log 2>&1 &
          sleep 10  # Give some time for services to start
          airflow dags list

      - name: Verify Deployment
        run: |
          source airflow_venv/bin/activate
          airflow dags list
          dbt test --profiles-dir ~/.dbt
